name: Build Community Icons
permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest
          target: Win64

        - name: macOS
          os: macos-latest
          target: MacOS

        - name: iOS
          os: macos-latest
          target: iOS

        - name: Android32
          os: ubuntu-22.04
          target: Android32

        - name: Android64
          os: ubuntu-22.04
          target: Android64

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          target: ${{ matrix.config.target }}
          combine: true
          sdk: v5.4.1 # Forcing a specific version prevents searching



  package:
    name: Package builds
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - uses:  actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: .
          merge-multiple: true

      - name: Combine Builds
        uses: geode-sdk/build-geode-mod/combine@main
        id: build

      - name: Upload Final Mod
        uses: actions/upload-artifact@v4
        with:
          name: Final-Mod
          path: ${{ steps.build.outputs.build-output }}
